insert into authors (name, lastname) values ('Derron', 'Playford');
insert into authors (name, lastname) values ('Jimmie', 'Hargreves');
insert into authors (name, lastname) values ('Anatole', 'Andrzejowski');
insert into authors (name, lastname) values ('Benita', 'Layland');
insert into authors (name, lastname) values ('Emyle', 'Doncom');
insert into authors (name, lastname) values ('Maurizio', 'Boath');
insert into authors (name, lastname) values ('Lynelle', 'Basant');
insert into authors (name, lastname) values ('Adolf', 'Kennion');
insert into authors (name, lastname) values ('Lindy', 'Abell');
insert into authors (name, lastname) values ('Marysa', 'Pearmain');
insert into authors (name, lastname) values ('Collete', 'Kenwrick');
insert into authors (name, lastname) values ('Adeline', 'Mansbridge');
insert into authors (name, lastname) values ('Kelbee', 'Rospars');
insert into authors (name, lastname) values ('Sibella', 'Powrie');
insert into authors (name, lastname) values ('Melvin', 'Marfield');
insert into authors (name, lastname) values ('Kory', 'Leipelt');
insert into authors (name, lastname) values ('Andromache', 'Waghorne');
insert into authors (name, lastname) values ('Nathalia', 'Harmour');
insert into authors (name, lastname) values ('Malva', 'Desson');
insert into authors (name, lastname) values ('Werner', 'Fansy');
insert into authors (name, lastname) values ('Natasha', 'Perkis');
insert into authors (name, lastname) values ('Stephi', 'Pear');
insert into authors (name, lastname) values ('Walker', 'Nyland');
insert into authors (name, lastname) values ('Elise', 'Peto');
insert into authors (name, lastname) values ('Fredek', 'Varren');
insert into authors (name, lastname) values ('Ash', 'Kobierra');
insert into authors (name, lastname) values ('Nikolos', 'Ironmonger');
insert into authors (name, lastname) values ('Simona', 'Alexsandrov');
insert into authors (name, lastname) values ('Carolyn', 'MacCarrane');
insert into authors (name, lastname) values ('Robinetta', 'Suart');



insert into books (title, author_id, isbn, available) values ('Big Fish', 30, '936272792-7', true);
insert into books (title, author_id, isbn, available) values ('Made for Each Other', 22, '658321512-8', true);
insert into books (title, author_id, isbn, available) values ('Yesterday Was a Lie', 12, '415198260-4', true);
insert into books (title, author_id, isbn, available) values ('T,O,U,C,H,I,N,G', 16, '158390798-X', true);
insert into books (title, author_id, isbn, available) values ('Foxfire', 6, '436244191-3', true);
insert into books (title, author_id, isbn, available) values ('Vampire Effect (The Twins Effect) (Chin gei bin)', 14, '534780967-1', true);
insert into books (title, author_id, isbn, available) values ('Faces of Schlock', 17, '980441634-4', true);
insert into books (title, author_id, isbn, available) values ('Return of Jafar, The', 3, '373168022-X', true);
insert into books (title, author_id, isbn, available) values ('Polite People (Kurteist fólk)', 30, '488173014-2', true);
insert into books (title, author_id, isbn, available) values ('Heartbreak Hotel', 8, '012696714-8', true);
insert into books (title, author_id, isbn, available) values ('Snow and Ashes', 3, '190934676-4', true);
insert into books (title, author_id, isbn, available) values ('Common Threads: Stories from the Quilt', 6, '020185793-6', true);
insert into books (title, author_id, isbn, available) values ('Swept from the Sea', 17, '770458027-2', true);
insert into books (title, author_id, isbn, available) values ('Saving Grace', 20, '466928937-3', true);
insert into books (title, author_id, isbn, available) values ('The Girl from Nagasaki', 15, '638412313-4', true);
insert into books (title, author_id, isbn, available) values ('Green Wave, The', 26, '469350716-4', true);
insert into books (title, author_id, isbn, available) values ('Woyzeck', 15, '342630923-8', true);
insert into books (title, author_id, isbn, available) values ('Essex Boys', 20, '420691762-0', true);
insert into books (title, author_id, isbn, available) values ('Jeremy', 27, '490616971-6', true);
insert into books (title, author_id, isbn, available) values ('Rocco and His Brothers (Rocco e i suoi fratelli)', 10, '869003250-9', true);
insert into books (title, author_id, isbn, available) values ('Ballad of Cable Hogue, The', 25, '152827813-5', true);
insert into books (title, author_id, isbn, available) values ('Just Visiting', 15, '565892810-9', true);
insert into books (title, author_id, isbn, available) values ('It Could Happen to You', 18, '603034343-2', true);
insert into books (title, author_id, isbn, available) values ('Brute, The (Bruto, El)', 16, '973220110-X', true);
insert into books (title, author_id, isbn, available) values ('Ivan Vasilievich: Back to the Future (Ivan Vasilievich menyaet professiyu)', 5, '158929775-X', true);
insert into books (title, author_id, isbn, available) values ('Battle of the Sexes, The', 29, '845300851-5', true);
insert into books (title, author_id, isbn, available) values ('People in Places', 21, '641797196-1', true);
insert into books (title, author_id, isbn, available) values ('Miracle', 13, '419300372-8', true);
insert into books (title, author_id, isbn, available) values ('Tammy and the T-Rex', 20, '241486367-6', true);
insert into books (title, author_id, isbn, available) values ('7 Faces of Dr. Lao', 9, '339942052-8', true);
insert into books (title, author_id, isbn, available) values ('Polisse', 2, '709861671-0', true);
insert into books (title, author_id, isbn, available) values ('Last Godfather, The', 27, '194142819-3', true);
insert into books (title, author_id, isbn, available) values ('Mystics in Bali (Leák)', 23, '515219059-1', true);
insert into books (title, author_id, isbn, available) values ('V.I.P.s, The', 13, '200374803-2', true);
insert into books (title, author_id, isbn, available) values ('Genocide (Konchû daisensô)', 1, '175026614-8', true);
insert into books (title, author_id, isbn, available) values ('Five Minarets in New York (Act of Vengeance) (Terrorist, The)', 25, '042792627-0', true);
insert into books (title, author_id, isbn, available) values ('Five Heartbeats, The', 27, '253197739-2', true);
insert into books (title, author_id, isbn, available) values ('Generation P', 26, '924988381-1', true);
insert into books (title, author_id, isbn, available) values ('Red''s Dream', 21, '073020115-5', true);
insert into books (title, author_id, isbn, available) values ('Human Family Tree, The', 13, '933094247-4', true);
insert into books (title, author_id, isbn, available) values ('Finding Normal', 2, '715975441-7', true);
insert into books (title, author_id, isbn, available) values ('Gone in 60 Seconds', 13, '281857112-X', true);
insert into books (title, author_id, isbn, available) values ('Signal, The', 22, '578242903-8', true);
insert into books (title, author_id, isbn, available) values ('Once Upon a Time in China II (Wong Fei-hung Ji Yi: Naam yi dong ji keung)', 13, '528287806-2', true);
insert into books (title, author_id, isbn, available) values ('It''s My Party', 12, '164987690-4', true);
insert into books (title, author_id, isbn, available) values ('Stone Cold', 22, '631879081-0', true);
insert into books (title, author_id, isbn, available) values ('Topo, El', 15, '668500505-X', true);
insert into books (title, author_id, isbn, available) values ('Tales from the Darkside: The Movie', 21, '213334669-4', true);
insert into books (title, author_id, isbn, available) values ('Hell Up in Harlem', 15, '880362142-3', true);
insert into books (title, author_id, isbn, available) values ('Chopper', 28, '847661683-X', true);
insert into books (title, author_id, isbn, available) values ('Hands Across the Table', 6, '125307561-1', true);
insert into books (title, author_id, isbn, available) values ('Birth of a Nation, The', 1, '812421143-4', true);
insert into books (title, author_id, isbn, available) values ('Slave of Love, A (Raba lyubvi)', 19, '576792575-5', true);
insert into books (title, author_id, isbn, available) values ('The Last Round', 26, '457202966-0', true);
insert into books (title, author_id, isbn, available) values ('Eagle Eye', 8, '640790190-1', true);
insert into books (title, author_id, isbn, available) values ('Bridge to Nowhere, The', 2, '920399617-6', true);
insert into books (title, author_id, isbn, available) values ('Hitcher, The', 10, '022493844-4', true);
insert into books (title, author_id, isbn, available) values ('Butter', 17, '474769395-5', true);
insert into books (title, author_id, isbn, available) values ('Sabrina', 28, '868718319-4', true);
insert into books (title, author_id, isbn, available) values ('Dirt', 18, '021386616-1', true);
insert into books (title, author_id, isbn, available) values ('Elegy', 21, '526328745-3', true);
insert into books (title, author_id, isbn, available) values ('Tuesdays with Morrie', 4, '243212586-X', true);
insert into books (title, author_id, isbn, available) values ('Fighting Seabees, The', 21, '717892556-6', true);
insert into books (title, author_id, isbn, available) values ('Four Brothers', 18, '573454151-6', true);
insert into books (title, author_id, isbn, available) values ('Dragonphoenix Chronicles: Indomitable, The', 7, '242541940-3', true);
insert into books (title, author_id, isbn, available) values ('Men with Guns', 22, '893672088-0', true);
insert into books (title, author_id, isbn, available) values ('Mission to Mir', 14, '317088285-6', true);
insert into books (title, author_id, isbn, available) values ('Sex in Chains (Geschlecht in Fesseln)', 17, '438130484-5', true);
insert into books (title, author_id, isbn, available) values ('Merry-Go-Round', 24, '730284615-4', true);
insert into books (title, author_id, isbn, available) values ('Idle Hands', 4, '215331885-8', true);
insert into books (title, author_id, isbn, available) values ('Breakfast on Pluto', 25, '026481292-1', true);
insert into books (title, author_id, isbn, available) values ('False Trail (Jägarna 2)', 3, '206652081-0', true);
insert into books (title, author_id, isbn, available) values ('Regular Guys (Echte Kerle)', 18, '866492786-3', true);
insert into books (title, author_id, isbn, available) values ('Shop Around the Corner, The', 18, '856683614-6', true);
insert into books (title, author_id, isbn, available) values ('Hawaii, Oslo', 4, '526347649-3', true);
insert into books (title, author_id, isbn, available) values ('I Know What You Did Last Summer', 25, '965961067-X', true);
insert into books (title, author_id, isbn, available) values ('Descent', 18, '622718821-2', true);
insert into books (title, author_id, isbn, available) values ('Vares: The Path of the Righteous Men (Vares - Kaidan tien kulkijat)', 14, '124192372-8', true);
insert into books (title, author_id, isbn, available) values ('Wild Things: Diamonds in the Rough', 27, '296032465-X', true);
insert into books (title, author_id, isbn, available) values ('Fifty-Fifty (a.k.a. Schizo) (Shiza)', 7, '643433850-3', true);
insert into books (title, author_id, isbn, available) values ('Lolita', 12, '031605529-8', true);
insert into books (title, author_id, isbn, available) values ('Dealin'' with Idiots', 12, '919244964-6', true);
insert into books (title, author_id, isbn, available) values ('The Violent Professionals', 19, '480625715-X', true);
insert into books (title, author_id, isbn, available) values ('Loved One, The', 18, '553491916-7', true);
insert into books (title, author_id, isbn, available) values ('High Tech, Low Life', 29, '200495639-9', true);
insert into books (title, author_id, isbn, available) values ('Inspector Gadget', 4, '434030676-2', true);
insert into books (title, author_id, isbn, available) values ('King of California', 5, '197549809-7', true);
insert into books (title, author_id, isbn, available) values ('Machine, The', 17, '018651371-2', true);
insert into books (title, author_id, isbn, available) values ('If Only', 20, '343868638-4', true);
insert into books (title, author_id, isbn, available) values ('Almost Married', 15, '141223670-3', true);
insert into books (title, author_id, isbn, available) values ('One Foot in Heaven', 6, '596640105-5', true);
insert into books (title, author_id, isbn, available) values ('Wreck-It Ralph', 2, '078248504-9', true);
insert into books (title, author_id, isbn, available) values ('Jericho Mile, The', 28, '425968241-5', true);
insert into books (title, author_id, isbn, available) values ('Better Tomorrow, A (Ying hung boon sik)', 5, '899032513-7', true);
insert into books (title, author_id, isbn, available) values ('Night at the Museum: Secret of the Tomb', 29, '162995876-X', true);
insert into books (title, author_id, isbn, available) values ('Age of the Dragons', 13, '151985354-8', true);
insert into books (title, author_id, isbn, available) values ('My Daughter, the Socialist (I kori mou, i sosialistria)', 16, '554081088-0', true);
insert into books (title, author_id, isbn, available) values ('There Be Dragons', 6, '540049720-9', true);
insert into books (title, author_id, isbn, available) values ('Double Jeopardy', 2, '013333841-X', true);
insert into books (title, author_id, isbn, available) values ('Standard Operating Procedure', 14, '810347824-5', true);
insert into books (title, author_id, isbn, available) values ('Blue Denim', 9, '366587516-1', true);
insert into books (title, author_id, isbn, available) values ('Jerry Springer: The Opera', 28, '739346655-4', true);
insert into books (title, author_id, isbn, available) values ('Kung Fu Panda Holiday Special', 5, '759957534-0', true);
insert into books (title, author_id, isbn, available) values ('Caesar (Julius Caesar)', 7, '910393982-0', true);
insert into books (title, author_id, isbn, available) values ('Gravedancers, The', 28, '172767670-X', true);
insert into books (title, author_id, isbn, available) values ('Justin Bieber: Never Say Never', 12, '966852853-0', true);
insert into books (title, author_id, isbn, available) values ('Waist Deep', 28, '653343749-6', true);
insert into books (title, author_id, isbn, available) values ('Immature, The (Immaturi)', 5, '914555524-9', true);
insert into books (title, author_id, isbn, available) values ('Six Degrees of Separation', 17, '006162324-5', true);
insert into books (title, author_id, isbn, available) values ('Silent Running', 6, '158048540-5', true);
insert into books (title, author_id, isbn, available) values ('President''s Man, The', 9, '330364966-9', true);
insert into books (title, author_id, isbn, available) values ('Shakespeare High', 20, '010073229-1', true);
insert into books (title, author_id, isbn, available) values ('Man Is Not a Bird (Covek nije tica)', 26, '390339378-9', true);
insert into books (title, author_id, isbn, available) values ('Música Campesina (Country Music)', 17, '036254604-5', true);
insert into books (title, author_id, isbn, available) values ('Under the Domim Tree (Etz Hadomim Tafus)', 26, '536252340-6', true);
insert into books (title, author_id, isbn, available) values ('Barbershop 2: Back in Business', 17, '801270397-1', true);
insert into books (title, author_id, isbn, available) values ('Sheep Eaters (Lampaansyöjät)', 8, '690240098-9', true);
insert into books (title, author_id, isbn, available) values ('Vampire Girl vs. Frankenstein Girl (Kyûketsu Shôjo tai Shôjo Furanken)', 23, '157090312-3', true);
insert into books (title, author_id, isbn, available) values ('Goal! III', 18, '731325559-4', true);
insert into books (title, author_id, isbn, available) values ('Hunting Party, The', 10, '916570034-1', true);
insert into books (title, author_id, isbn, available) values ('Saving Private Ryan', 2, '612121592-5', true);
insert into books (title, author_id, isbn, available) values ('State Property', 29, '373961218-5', true);
insert into books (title, author_id, isbn, available) values ('Ecstasy in Entropy', 16, '655928076-4', true);
insert into books (title, author_id, isbn, available) values ('Riot on Sunset Strip', 12, '146656467-9', true);
insert into books (title, author_id, isbn, available) values ('Wheelmen', 1, '828262635-X', true);
insert into books (title, author_id, isbn, available) values ('Novena, The (La neuvaine)', 9, '399603185-8', true);
insert into books (title, author_id, isbn, available) values ('Long John Silver', 2, '365596483-8', true);
insert into books (title, author_id, isbn, available) values ('Outside Providence', 16, '141970590-3', true);
insert into books (title, author_id, isbn, available) values ('Leave Her to Heaven', 6, '295373765-0', true);
insert into books (title, author_id, isbn, available) values ('Pure Country', 8, '221645197-5', true);
insert into books (title, author_id, isbn, available) values ('Momma''s Man', 21, '952821815-6', true);
insert into books (title, author_id, isbn, available) values ('Innocent, The (Innocente, L'')', 20, '477060444-0', true);
insert into books (title, author_id, isbn, available) values ('My New Gun', 15, '543458698-0', true);
insert into books (title, author_id, isbn, available) values ('Damned the Day I Met You', 11, '202825133-6', true);
insert into books (title, author_id, isbn, available) values ('Story of Me, The (O contador de histórias)', 11, '847358183-0', true);
insert into books (title, author_id, isbn, available) values ('Wrong Move, The (Falsche Bewegung)', 24, '984790045-0', true);
insert into books (title, author_id, isbn, available) values ('Beyond Tomorrow (Beyond Christmas)', 16, '451852391-1', true);
insert into books (title, author_id, isbn, available) values ('Runner Runner', 25, '056183311-7', true);
insert into books (title, author_id, isbn, available) values ('Whisper of the Heart (Mimi wo sumaseba)', 20, '924700050-5', true);
insert into books (title, author_id, isbn, available) values ('Turtle''s Tale: Sammy''s Adventures, A', 11, '452974819-7', true);
insert into books (title, author_id, isbn, available) values ('Corporation, The', 10, '999690435-0', true);
insert into books (title, author_id, isbn, available) values ('Criss Cross', 9, '430596246-2', true);
insert into books (title, author_id, isbn, available) values ('Overlord', 22, '052851751-1', true);
insert into books (title, author_id, isbn, available) values ('Balls of Fury', 26, '076171441-3', true);
insert into books (title, author_id, isbn, available) values ('Imposter, The', 29, '106052667-0', true);
insert into books (title, author_id, isbn, available) values ('All Quiet on the Western Front', 4, '165463338-0', true);
insert into books (title, author_id, isbn, available) values ('Return of the Vampire, The', 12, '673592827-X', true);
insert into books (title, author_id, isbn, available) values ('Hen Hop', 16, '371977655-7', true);
insert into books (title, author_id, isbn, available) values ('Sitter, The', 30, '568409593-3', true);
insert into books (title, author_id, isbn, available) values ('Rent', 11, '847456141-8', true);
insert into books (title, author_id, isbn, available) values ('When Nietzsche Wept', 6, '811430654-8', true);
insert into books (title, author_id, isbn, available) values ('The Scapegoat', 19, '558227637-8', true);
insert into books (title, author_id, isbn, available) values ('Sushi Girl', 11, '735012724-3', true);
insert into books (title, author_id, isbn, available) values ('Affair in Trinidad', 19, '741155987-3', true);
insert into books (title, author_id, isbn, available) values ('Rain Over Santiago (Il pleut sur Santiago)', 30, '774465532-X', true);
insert into books (title, author_id, isbn, available) values ('Zombie Apocalypse', 22, '760520378-0', true);
insert into books (title, author_id, isbn, available) values ('Accepted', 9, '801649585-0', true);
insert into books (title, author_id, isbn, available) values ('Above the Rim', 17, '300657717-5', true);
insert into books (title, author_id, isbn, available) values ('Cassandra''s Dream', 2, '997763636-2', true);
insert into books (title, author_id, isbn, available) values ('City Hall', 30, '493228195-1', true);
insert into books (title, author_id, isbn, available) values ('Cohen and Tate', 20, '221173855-9', true);
insert into books (title, author_id, isbn, available) values ('Touchy Feely', 13, '487371714-0', true);
insert into books (title, author_id, isbn, available) values ('50 First Dates', 20, '897492874-4', true);
insert into books (title, author_id, isbn, available) values ('North', 20, '167905674-3', true);
insert into books (title, author_id, isbn, available) values ('Pont du Nord, Le', 18, '941018387-1', true);
insert into books (title, author_id, isbn, available) values ('Quod erat demonstrandum', 28, '487323280-5', true);
insert into books (title, author_id, isbn, available) values ('Deliver Us from Evil', 26, '447518093-7', true);
insert into books (title, author_id, isbn, available) values ('Ong-Bak: The Thai Warrior (Ong Bak)', 12, '347377788-9', true);
insert into books (title, author_id, isbn, available) values ('Nobody''s Fool', 14, '575164551-0', true);
insert into books (title, author_id, isbn, available) values ('Lawless Heart, The', 25, '530436463-5', true);
insert into books (title, author_id, isbn, available) values ('Dunce Class on Vacation, The (Hababam sinifi tatilde)', 19, '978388745-9', true);
insert into books (title, author_id, isbn, available) values ('Romper Stomper', 26, '407239063-1', true);
insert into books (title, author_id, isbn, available) values ('Sex and Breakfast', 25, '795236529-0', true);
insert into books (title, author_id, isbn, available) values ('Don''t Bother to Knock', 15, '589831178-5', true);
insert into books (title, author_id, isbn, available) values ('Brain Damage', 9, '502947515-X', true);
insert into books (title, author_id, isbn, available) values ('Cimarron Kid, The', 21, '849541332-9', true);
insert into books (title, author_id, isbn, available) values ('War of the Dead - Stone''s War ', 29, '391084907-5', true);
insert into books (title, author_id, isbn, available) values ('Black Book (Zwartboek)', 24, '202092706-3', true);
insert into books (title, author_id, isbn, available) values ('Tim and Eric''s Billion Dollar Movie', 15, '245340434-2', true);
insert into books (title, author_id, isbn, available) values ('Meatballs 4', 22, '843115554-X', true);
insert into books (title, author_id, isbn, available) values ('American Pie Presents: The Book of Love (American Pie 7: The Book of Love)', 8, '706183965-1', true);
insert into books (title, author_id, isbn, available) values ('Big Easy, The', 20, '403420946-1', true);
insert into books (title, author_id, isbn, available) values ('Summer of Sam', 7, '721930664-4', true);
insert into books (title, author_id, isbn, available) values ('Panic Button', 15, '166170669-X', true);
insert into books (title, author_id, isbn, available) values ('4 Horsemen of the Apocalypse, The', 3, '236847144-8', true);
insert into books (title, author_id, isbn, available) values ('Stuart Little 2', 15, '718369232-9', true);
insert into books (title, author_id, isbn, available) values ('Hunt For Gollum, The', 25, '754055993-4', true);
insert into books (title, author_id, isbn, available) values ('Resistance', 9, '297009401-0', true);
insert into books (title, author_id, isbn, available) values ('Faces of Death', 28, '923524116-2', true);
insert into books (title, author_id, isbn, available) values ('Russia House, The', 22, '684903374-3', true);
insert into books (title, author_id, isbn, available) values ('Freeway', 8, '935904086-X', true);
insert into books (title, author_id, isbn, available) values ('Last Days in the Desert', 19, '305444450-3', true);
insert into books (title, author_id, isbn, available) values ('Gone Nutty', 3, '972777703-1', true);
insert into books (title, author_id, isbn, available) values ('Prime Suspect: The Lost Child', 26, '589401405-0', true);
insert into books (title, author_id, isbn, available) values ('Innocence', 8, '489278638-1', true);
insert into books (title, author_id, isbn, available) values ('Devil to Pay!, The', 3, '800835987-0', true);
insert into books (title, author_id, isbn, available) values ('Alien: Resurrection', 19, '338413997-6', true);
insert into books (title, author_id, isbn, available) values ('Platinum Blonde', 28, '288163769-8', true);
insert into books (title, author_id, isbn, available) values ('Spin', 12, '819100418-6', true);
insert into books (title, author_id, isbn, available) values ('Balzac and the Little Chinese Seamstress (Xiao cai feng)', 22, '249893449-9', true);
insert into books (title, author_id, isbn, available) values ('Up', 19, '580175194-7', true);
insert into books (title, author_id, isbn, available) values ('The Wrecking Crew', 21, '088027530-8', true);
insert into books (title, author_id, isbn, available) values ('Boomerang', 28, '715935350-1', true);
insert into books (title, author_id, isbn, available) values ('Studentfesten', 4, '680970006-4', true);
insert into books (title, author_id, isbn, available) values ('Black Roses ', 23, '772362718-1', true);
insert into books (title, author_id, isbn, available) values ('A Short History of Decay', 12, '037727324-4', true);
insert into books (title, author_id, isbn, available) values ('Eat Sleep Die (Äta sova dö)', 27, '772607088-9', true);
insert into books (title, author_id, isbn, available) values ('Black Dahlia, The', 5, '411788767-X', true);
insert into books (title, author_id, isbn, available) values ('Personal Journey with Martin Scorsese Through American Movies, A', 10, '102596973-1', true);
insert into books (title, author_id, isbn, available) values ('Scene at the Sea, A (Ano natsu, ichiban shizukana umi)', 9, '770519342-6', true);
insert into books (title, author_id, isbn, available) values ('Caught Up', 29, '785240068-X', true);
insert into books (title, author_id, isbn, available) values ('Girl Who Played with Fire, The (Flickan som lekte med elden)', 14, '969053775-X', true);
insert into books (title, author_id, isbn, available) values ('Malibu High', 26, '964518547-5', true);
insert into books (title, author_id, isbn, available) values ('Shadow of the Thin Man', 27, '829965213-8', true);
insert into books (title, author_id, isbn, available) values ('Carolina', 29, '690799818-1', true);
insert into books (title, author_id, isbn, available) values ('Godzilla vs. Megalon (Gojira tai Megaro)', 8, '854456539-5', true);
insert into books (title, author_id, isbn, available) values ('Happy Gilmore', 8, '341631012-8', true);
insert into books (title, author_id, isbn, available) values ('Mrs. Winterbourne', 9, '043693878-2', true);
insert into books (title, author_id, isbn, available) values ('Parking Lot Movie, The', 15, '561522956-X', true);
insert into books (title, author_id, isbn, available) values ('Sea Gull, The', 5, '305449753-4', true);
insert into books (title, author_id, isbn, available) values ('Wayward Bus, The', 14, '031058793-X', true);
insert into books (title, author_id, isbn, available) values ('Prodigal Sons', 24, '159678322-2', true);
insert into books (title, author_id, isbn, available) values ('The Way He Looks', 3, '924600274-1', true);
insert into books (title, author_id, isbn, available) values ('Blood of the Beasts (Sang des bêtes, Le)', 23, '266413944-4', true);
insert into books (title, author_id, isbn, available) values ('Age of Tomorrow', 23, '409251540-5', true);
insert into books (title, author_id, isbn, available) values ('De-Lovely', 3, '938286867-4', true);
insert into books (title, author_id, isbn, available) values ('Motocrossed', 7, '561484669-7', true);
insert into books (title, author_id, isbn, available) values ('Game of Death', 28, '378000245-0', true);
insert into books (title, author_id, isbn, available) values ('Trust', 4, '440438547-1', true);
insert into books (title, author_id, isbn, available) values ('Errors of the Human Body ', 4, '718480430-9', true);
insert into books (title, author_id, isbn, available) values ('Blondie of the Follies', 22, '981596725-8', true);
insert into books (title, author_id, isbn, available) values ('Just Imagine', 14, '442921088-8', true);
insert into books (title, author_id, isbn, available) values ('Sleepers', 4, '452841709-X', true);
insert into books (title, author_id, isbn, available) values ('Young Törless, The (Junge Törless, Der)', 30, '743485706-4', true);
insert into books (title, author_id, isbn, available) values ('Little Lili (La petite Lili)', 7, '094922797-8', true);
insert into books (title, author_id, isbn, available) values ('House of Small Cubes, The (Tsumiki no ie)', 25, '917108249-2', true);
insert into books (title, author_id, isbn, available) values ('Single White Female', 27, '929483937-0', true);
insert into books (title, author_id, isbn, available) values ('Misunderstood', 19, '970607016-8', true);
insert into books (title, author_id, isbn, available) values ('Mondovino', 10, '107175229-4', true);
insert into books (title, author_id, isbn, available) values ('G.I. Joe: The Movie', 17, '750086179-6', true);
insert into books (title, author_id, isbn, available) values ('Woman of Antwerp', 5, '564205943-2', true);
insert into books (title, author_id, isbn, available) values ('Whiteboyz', 21, '869745323-2', true);
insert into books (title, author_id, isbn, available) values ('Supercondriaque', 21, '127182345-4', true);
insert into books (title, author_id, isbn, available) values ('Samurai Fiction (SF: Episode One)', 9, '613552737-1', true);
insert into books (title, author_id, isbn, available) values ('Fathers'' Day', 25, '889502095-2', true);
insert into books (title, author_id, isbn, available) values ('Halloween is Grinch Night', 8, '088243724-0', true);
insert into books (title, author_id, isbn, available) values ('Dirty Ho (Lan tou He)', 23, '106777886-1', true);
insert into books (title, author_id, isbn, available) values ('Scalphunters, The', 29, '865060445-5', true);
insert into books (title, author_id, isbn, available) values ('The Lone Ranger', 30, '462855566-4', true);
insert into books (title, author_id, isbn, available) values ('Killer McCoy', 14, '158506113-1', true);
insert into books (title, author_id, isbn, available) values ('Melissa P.', 23, '128949739-7', true);
insert into books (title, author_id, isbn, available) values ('Filthy Gorgeous: The Bob Guccione Story', 29, '254359989-4', true);
insert into books (title, author_id, isbn, available) values ('Act in Question, The (Acto en cuestión, El)', 21, '617483337-2', true);
insert into books (title, author_id, isbn, available) values ('Blow Job', 2, '785116622-5', true);
insert into books (title, author_id, isbn, available) values ('I Woke Up Early the Day I Died', 5, '327912922-2', true);
insert into books (title, author_id, isbn, available) values ('Illusionist, The', 12, '514821744-8', true);
insert into books (title, author_id, isbn, available) values ('Nurse Betty', 18, '295142737-9', true);
insert into books (title, author_id, isbn, available) values ('Gimme Shelter', 24, '669126849-0', true);
insert into books (title, author_id, isbn, available) values ('Invisible Waves', 15, '908548616-5', true);
insert into books (title, author_id, isbn, available) values ('Fisher King, The', 19, '292493048-0', true);
insert into books (title, author_id, isbn, available) values ('Ned Kelly', 11, '157392062-2', true);
insert into books (title, author_id, isbn, available) values ('Holy Smoke', 19, '369328336-2', true);
insert into books (title, author_id, isbn, available) values ('In the Winter Dark', 12, '916069646-X', true);
insert into books (title, author_id, isbn, available) values ('Pick-up Summer (Pinball Summer)', 3, '658892097-0', true);
insert into books (title, author_id, isbn, available) values ('NeverEnding Story III, The', 26, '584129666-3', true);
insert into books (title, author_id, isbn, available) values ('In Two Minds', 16, '553393608-4', true);
insert into books (title, author_id, isbn, available) values ('Story of Women (Affaire de femmes, Une)', 22, '126617868-6', true);
insert into books (title, author_id, isbn, available) values ('Kitchen in Paris', 23, '496863097-2', true);
insert into books (title, author_id, isbn, available) values ('James Gandolfini: Tribute to a Friend', 23, '003363685-0', true);
insert into books (title, author_id, isbn, available) values ('Manhunt', 26, '650334607-7', true);
insert into books (title, author_id, isbn, available) values ('Kaspar Hauser', 18, '669843965-7', true);
insert into books (title, author_id, isbn, available) values ('Dance with the Devil (Perdita Durango)', 20, '685096435-6', true);
insert into books (title, author_id, isbn, available) values ('Palme', 9, '157306982-5', true);
insert into books (title, author_id, isbn, available) values ('Thief Who Came to Dinner, The', 18, '220886599-5', true);
insert into books (title, author_id, isbn, available) values ('Dog Pound', 28, '715511347-6', true);
insert into books (title, author_id, isbn, available) values ('The Hatchet Man', 12, '492356857-7', true);
insert into books (title, author_id, isbn, available) values ('Burn Paris Burn', 1, '562446957-8', true);
insert into books (title, author_id, isbn, available) values ('Elevator ', 28, '557975349-7', true);
insert into books (title, author_id, isbn, available) values ('Mr Bones 2: Back from the Past', 11, '246038581-1', true);
insert into books (title, author_id, isbn, available) values ('Educating Rita', 9, '124920345-7', true);
insert into books (title, author_id, isbn, available) values ('Signs of Life (Lebenszeichen)', 14, '934937452-8', true);
insert into books (title, author_id, isbn, available) values ('Immortel (ad vitam) (Immortal)', 13, '010312551-5', true);
insert into books (title, author_id, isbn, available) values ('Dirty Deeds', 10, '994732509-1', true);
insert into books (title, author_id, isbn, available) values ('Destruction Force', 4, '730962839-X', true);
insert into books (title, author_id, isbn, available) values ('Wisdom of Crocodiles, The (a.k.a. Immortality)', 18, '376773644-6', true);
insert into books (title, author_id, isbn, available) values ('Amar Akbar Anthony', 29, '049838724-0', true);
insert into books (title, author_id, isbn, available) values ('Way You Wanted Me, The (Sellaisena kuin sinä minut halusit)', 6, '103453977-9', true);
insert into books (title, author_id, isbn, available) values ('What the Day Owes the Night', 28, '088582469-5', true);
insert into books (title, author_id, isbn, available) values ('In Search of a Midnight Kiss', 9, '678808189-1', true);
insert into books (title, author_id, isbn, available) values ('The Walking Hills', 28, '006168357-4', true);
insert into books (title, author_id, isbn, available) values ('Challenge, The', 2, '445107994-2', true);
insert into books (title, author_id, isbn, available) values ('Begotten', 10, '912390087-3', true);
insert into books (title, author_id, isbn, available) values ('Star for Two, A', 18, '005123991-4', true);
insert into books (title, author_id, isbn, available) values ('Stage Fright', 15, '289229594-7', true);
insert into books (title, author_id, isbn, available) values ('Thelma & Louise', 11, '517245326-1', true);
insert into books (title, author_id, isbn, available) values ('Feet First', 7, '207251439-8', true);
insert into books (title, author_id, isbn, available) values ('Clockwork Orange, A', 21, '386644127-4', true);
insert into books (title, author_id, isbn, available) values ('Inauguration of the Pleasure Dome', 2, '962209155-5', true);
insert into books (title, author_id, isbn, available) values ('Jason Becker: Not Dead Yet', 10, '784436445-9', true);
insert into books (title, author_id, isbn, available) values ('Questo piccolo grande amore', 11, '650378363-9', true);
